use_frameworks!

platform :ios, '8.0'

target 'HSYDatabaseToolsKit_Example' do
  pod 'HSYDatabaseToolsKit', :path => '../'

  target 'HSYDatabaseToolsKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
