use_frameworks!

platform :ios, '8.0'

target 'HSYDatabaseToolsKit_Example' do
  pod 'HSYDatabaseToolsKit', :path => '../'

  target 'HSYDatabaseToolsKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
    pod 'HSYMacroKit', :git=> 'https://github.com/huangsongyao/HSYMacroKit.git'
    pod 'HSYMethodsToolsKit', :git=> 'https://github.com/huangsongyao/HSYMethodsToolsKit.git'
    
  end
end
